### ISSUE TITLE
Right click options leaves aftermath after closing.

### ISSUE THREAD

**Issue by ErrolFernandes** [elementary/website#2815] opened 2021-08-24 14:26 UTC
## What Happened

In desktop after closing the right click options the options menu leaves back the right side of the options.

## Expected Behavior

the aftermath residue should not be present.

## Steps to Reproduce

1.right click on the mouse in desktop or homepage.
2.close the options by clicking in some other plain space on the same page.
3.
![photo_2021-08-24_14-19-04](https://user-images.githubusercontent.com/83249470/130634575-156ca2ea-319d-4fc0-8e98-ff0123d0b476.jpg)

**Comment by cassidyjames** [comment] 2021-08-27 23:29
This is the issue repo for the website itself. Regardless, it looks like this is a duplicate of https://github.com/elementary/os-patches/issues/80

**Closed by cassidyjames** 2021-08-27 23:29 UTC
Labels: Status: Out of Scope
