### ISSUE TITLE
Licenses in Getting Started doc

### ISSUE THREAD

**Issue by peteruithoven** [elementary/website#1888] opened 2018-02-02 10:28 UTC
Following the getting started I ended up with 2 versions of the GPL license:

- [debian/copyright](https://github.com/elementary/debian-template/blob/master/debian/copyright): GPL-3.0+
- [src/* (GPL header)](https://elementary.io/docs/code/reference#gpl-header): GPL-2.0+ (I'm no license expert, maybe this is more a GPL generic license)
- [COPYING](http://www.gnu.org/licenses/gpl-3.0.txt): GPL-2.0+

Following conventions I saw in other apps I also added the license to:
- meson.build
- appdata.xml

Shouldn't we switch all licenses to GPL-3.0+? Looking through the apps on the AppCenter that's what most people use. If GPL-2.0 is preferred we should probably alter the [debian/copyright](https://github.com/elementary/debian-template/blob/master/debian/copyright) file.

**Comment by lewisgoddard** [comment] 2019-10-25 23:18
Closing as duplicate of #1634

**Closed by lewisgoddard** 2019-10-25 23:18 UTC
Labels: Status: Duplicate
