### ISSUE TITLE
Recommend Etcher for all platforms

### ISSUE THREAD

**Issue by brainscript** [elementary/website#1643] opened 2017-04-11 09:28 UTC
The [installation page](https://elementary.io/docs/installation#creating-an-installation-medium) currently recommends three different programs for creating bootable installation mediums depending on the selected operating system.

[Etcher](https://etcher.io/) is only recommended when you select MacOS. The options for Windows and Ubuntu are currently [Rufus](https://rufus.akeo.ie/) and [UNetbootin](https://unetbootin.github.io). Both of them **look** very complicated and terms like "partition scheme" and "cluster size" sound very scary to inexperienced users making them feel like they might be doing something wrong.

The only benefit of Rufus and UNetbootin is the possibility to automatically install specific distributions (like FreeDOS). That feature is completely unnecessary for installing elementary OS.

That's why I would remove them and **only recommend Etcher for all platforms** making it easier and especially less scary installing the elementary OS image. And when Etcher launches [their image catalog](https://resin.io/blog/the-future-of-etcher/) elementary OS could be published there for an even simpler installation process.

![](https://etcher.io/static/images/product.gif)

*Please let me know what you think about my suggestion, so I can make the change myself if you like it.*

**Comment by png2378** [comment] 2017-04-11 09:35
Possible duplicate of https://github.com/elementary/website/issues/1489.

**Comment by brainscript** [comment] 2017-04-11 09:41
@png2378 Yes, you're right. Sadly there wasn't yet made a decision there either.

**Closed** 2017-04-11 16:52 UTC
