### ISSUE TITLE
Broken link for beta downloading

### ISSUE THREAD

**Issue by somal** [elementary/website#2030] opened 2018-08-17 07:53 UTC
### Expected behavior

Beta downloading via https

### Actual behavior

The site by link is unreacheable

### Steps to reproduce the behavior

1. Go to https://developer.elementary.io/#beta
2. Click on "Download via HTTPS"

### System information

- **Operating system**: EoS
- **Operating system version**: Loki
- **Browser**:  Chrome
- **Browser version**: 
- **Enabled Browser Extensions**:

**Comment by btkostner** [comment] 2018-08-17 15:34
Is there anything in your console logs? You can press F12 to get the developer tabs up, then click console to view the logs.

**Comment by somal** [comment] 2018-08-19 05:15
![screenshot from 2018-08-19 08-15-10](https://user-images.githubusercontent.com/5236713/44305727-0b951700-a388-11e8-8322-e71b0e1476ee.png)
![screenshot from 2018-08-19 08-15-06](https://user-images.githubusercontent.com/5236713/44305728-0b951700-a388-11e8-8b9d-b034723386b5.png)

**Comment by btkostner** [comment] 2018-08-19 19:57
I can confirm that that link is correct and working. Is it possible that there is some firewall on your network that is blocking you?

**Comment by peterthomashorn** [comment] 2018-08-28 13:50
It probably is related to #1876 which I just stumbled over. Some CloudFlare IPs are blocked in Russia, @somal

**Comment by btkostner** [comment] 2018-08-28 15:08
I'm going to close this because it's probably a network level issue and something we can not fix. Feel free to re-open it if you have any more information that points to this not being a network issue.

**Closed by btkostner** 2018-08-28 15:08 UTC

**Comment by somal** [comment] 2018-09-11 15:07
Yes, Its Russian network problem.
Thanks for all
