### ISSUE TITLE
Cant download

### ISSUE THREAD

**Issue by aethezxd** [elementary/website#2208] opened 2019-05-30 13:10 UTC
### Expected behavior
To be able to download it.
Changing the amount to $0.

### Actual behavior
Nothing happening.
The "download" link is saying that I need to buy it and when I click it nothing happens.
### Steps to reproduce the behavior

1. Click on pay what you want and put 0.
2. Try to click on the "Download" button that says that I need to download it
3. Nothing happens.

### System information

- **Operating system**: Windows
- **Operating system version**: 1809
- **Browser**: Brave
- **Browser version**: Latest
- **Enabled Browser Extensions**:Lastpass

Tried with microsoft edge out of the box.

**Comment by peteruithoven** [comment] 2019-05-30 13:43
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/website/issues/2201

**Comment by aethezxd** [comment] 2019-05-30 13:44
Is there a way to get the download link?

**Closed** 2019-10-25 23:50 UTC
