### ISSUE TITLE
to download a distribution without payment ;-)

### ISSUE THREAD

**Issue by Qvazarius** [elementary/website#1882] opened 2018-01-25 23:23 UTC
_If you enter the amount_ **0,000 USD** _is download a distribution without payment_ ;-)

screenshot 0.00 USD  https://screenshots.firefox.com/QiurVcvomlZU0GkE/elementary.io
screenshot 0.000 USD https://screenshots.firefox.com/qbosbSTngNsvqIm9/elementary.io

**Comment by lewisgoddard** [comment] 2018-01-26 01:27
Both of these let me download for free here. What localisation is that?

**Comment by png2378** [comment] 2018-01-26 03:37
1. "Purchase elementary OS"
2. "Download elementary OS"

**Comment by lewisgoddard** [comment] 2018-01-26 09:55
I understand what it says, but was wondering what localisation it was to see if it was somehow interfering with our number detection.

**Comment by sirkadirov** [comment] 2018-01-31 18:00
@lewisgoddard it is russian. I checked it, but all works great...

**Comment by lewisgoddard** [comment] 2018-01-31 22:57
Okay, I'm going to close this as incomplete since I cannot reproduce on elementary.io/ru/ and a definitive URL was not provided.

**Closed by lewisgoddard** 2018-01-31 22:57 UTC
Labels: Status: Incomplete
