### ISSUE TITLE
Purchase button not working

### ISSUE THREAD

**Issue by devlinarptiw** [elementary/website#2806] opened 2021-08-19 16:04 UTC
### Expected behavior

Clicking purchase button to lead to download page or link or start download

### Actual behavior

Nothing happens

### Steps to reproduce the behavior

1. Open elementary.io
2. Click purchase button for Odin 6.0
3. Change amount or use custom amount - to no avail

### System information

- **Operating system**: Windows 10
- **Operating system version**: 
- **Browser**: Chrome
- **Browser version**:  92.0.4515.159
- **Enabled Browser Extensions**:

**Comment by vmstan** [comment] 2021-09-04 15:55
Seeing the same last night. Didn't work on Safari 15, but did on Microsoft Edge. (Mac)

**Comment by lewisgoddard** [comment] 2021-09-05 18:15
Unable to reproduce in Chrome on Windows or Safari on mac OS.

**Comment by M4rk3h** [comment] 2021-09-07 20:54
I had something similar in Edge on Kubuntu -  #2796. 

I ended up closing the issue as I was unable to replicate it after updating Edge.

**Comment by markorapaic** [comment] 2021-12-14 10:31
I am also experiencing the issue - running Chrome Version 96.0.4664.110 (Official Build) (64-bit) - here is the console error:

![Screenshot from 2021-12-14 20-53-56](https://user-images.githubusercontent.com/5222635/145980321-816d217c-dad6-4855-a2b1-4b2114add82b.png)

I am not able to download Odin by clicking on the download button - changing the price doesn't help as mentioned earlier.

I'm also unable to download Odin in Firefox 95.0 (64-bit), although the TypeError message is different:

![Screenshot from 2021-12-14 20-56-12](https://user-images.githubusercontent.com/5222635/145980762-5ef71c73-5f53-4a2c-9d42-9156c10448ae.png)

I am running elementary OS 5.1.7 Hera. Looks like something funky in `download.js`.

Thanks!

**Comment by lewisgoddard** [comment] 2021-12-19 21:26
I'm going to merge this with #2908 as I think it is the same issue, we might need to re-work the sentry tracking so I can actually dig into this.

**Closed by lewisgoddard** 2021-12-19 21:26 UTC
Labels: Status: Incomplete
