### ISSUE TITLE
Video freezing in youtube,facebook 

### ISSUE THREAD

**Issue by ahs95** [elementary/website#2159] opened 2019-02-14 15:05 UTC
When I watch videos on youtube, facebook and any other video sharing websites using chrome or epiphany the video freezes. When I do nothing for a few minutes and I have to move the mouse so that the video continues.
Version - elementary os 5 (juno) 
It would be better if the bug will be fixed quickly!
Thanks in advance.

**Comment by peteruithoven** [comment] 2019-02-14 23:52
Thanks for the report! I'm afraid this is a duplicate of https://github.com/elementary/os/issues/121
Also this is the repository for the elementary OS website. 
Please refrain from using !'s it usually comes across as rude.

**Closed** 2019-02-14 23:54 UTC
Labels: Status: Invalid

**Comment by ahs95** [comment] 2019-02-16 17:51
I didn't know that.
Extremely sorry.
