### ISSUE TITLE
Header of website is not responsive

### ISSUE THREAD

**Issue by akhil888binoy** [elementary/website#3243] opened 2023-05-01 10:53 UTC
### What Happened?

The Header seems to have a scroll bar while the size of screen is reduced 

### Steps to Reproduce

By reducing the size of screen we can observe this issue

### Expected Behavior

Need to avoid the scroller and add responsive design to it

### OS Version

7.x (Horus)

### Software Version

Latest release (I have run all updates)

**Comment by colinkiama** [comment] 2023-06-22 09:20
Duplicate of #3056

**Closed** 2023-06-25 14:56 UTC
