### ISSUE TITLE
Creating a Bootable Installer DVD for MacOS

### ISSUE THREAD

**Issue by rmcaninch** [elementary/website#2031] opened 2018-08-17 21:43 UTC
### Expected behavior

Create a bootable installer DVD on MacOS for a Mac that won't boot from USB.

### Actual behavior

This line from the docs:

> To create one, insert a blank DVD, right click on the ISO file in Finder, and select "Burn elementaryos-0.4.1-stable.20180214.iso to Disc".

Results in a copy of the ISO to the DVD media. The disk image is not written as a bootable image.

It should probably describe opening Disk Utility (Applications: Utilities) and selecting Burn, then picking the elementaryOS ISO. This is the case for an older iMac with MacOS 10.9.5 that still has an optical drive in it. I don't have an external SuperDrive handy to see what Disk Utility would look like on MacOS Sierra or newer. However I was not able to complete the install on an old Macbook Pro so I'm not certain if it was the media or if the machine is too old for the installer.

**Comment by bumper314** [comment] 2019-10-27 12:36
I can confirm these instructions do NOT work correctly on macOS 10.9.
However, they DO WORK on macOS 10.15.

I believe these instructions will work on macOS 10.11 and above, but I could test more to confirm.

---

It seems that in macOS 10.11, [Apple removed the ability to burn ISOs from Disk Utility](http://osxdaily.com/2015/11/22/burn-disc-images-os-x-finder/), but gave Finder the ability instead.  When you right-click on an ISO in Finder, you get the `Burn Disk Image "foo.iso" to Disk…` menu option.  In versions of macOS prior to 10.11, the menu would say `Burn "foo.iso" to Disk…` which would gives you the unwanted result of burning the ISO as a file to the DVD.

Writing clear instructions for burning an ISO to DVD and booting from it would take a whole article as the instructions will vary depending on which version of macOS you're running and what Apple hardware you have (and some users might not even know their OS version, so now you need instructions on how to check your version, etc. etc.).

Further, a Mac will not boot from a DVD without intervention.  You must hold the Option key when powering on to boot from a DVD.  To complicate things further, depending on your keyboard, the Mac might not register holding the Option key (this is true for older bluetooth Apple branded keyboards and some wireless Logitech keyboards), making it impossible to boot from the DVD.

FURTHER, when you boot from the DVD, you are presented with two options, "Windows" and "EFI Boot."  Choosing "Windows", you get a blank screen without backlight and the DVD will spin forever, so you don't know it's not working.  Choosing "EFI Boot", you get the grub bootloader.  Choosing an option from grub then gives you a blank screen with backlight for ~10 min until it finally shows the desktop, so be prepared to wait.

---

So how prepared are we to document all that?  I suggest just updating the existing instructions to read:

> If your Mac doesn't recognize your elementary OS USB Install Drive in the boot menu, you may need to create an elementary OS Install DVD instead. To create one on macOS 10.11 and above, insert a blank DVD, right click on the ISO file in Finder, and select "Burn Disk Image “elementaryos-5.0-stable.20181016.iso” to Disc". When complete, attempt to boot again from the Install DVD by holding the Option key while powering on and choosing "EFI Boot" from the boot options.

**Comment by lewisgoddard** [comment] 2019-10-28 17:42
I'm going to assume this is quite a low priority if any mac with an OS that has been updated in the last 4 years is supported. I'm not sure how macs that have been EOL stack up against elementary OS's minimum requirements.

**Comment by danrabbit** [comment] 2020-07-22 17:50
I'm going to close this since we now recommend creating a bootable USB with Etcher

**Closed by danrabbit** 2020-07-22 17:50 UTC
Labels: Needs Documenting, Priority: Wishlist, System: macOS
