### ISSUE TITLE
Slack links do not resolve

### ISSUE THREAD

**Issue by dar5hak** [elementary/website#2759] opened 2021-06-30 05:38 UTC
## What Happened

The following links are not resolved:
- https://community-slack.elementary.io/
- https://translators-slack.elementary.io/

However, the non-custom-domain counterparts work fine:
- https://elementarycommunity.slack.com/
- I don't know the URL for Translators Slack.

## Expected Behavior

These links should work.

## Steps to Reproduce

1. Go to https://elementary.io/ homepage
2. Click on Slack icon in header

### Logs

NA

## Platform Information

Firefox 89

**Comment by btkostner** [comment] 2021-07-01 16:55
Duplicate of #2714

**Closed by btkostner** 2021-07-01 16:55 UTC
