### ISSUE TITLE
Free download call-to-action button

### ISSUE THREAD

**Issue by frasza** [elementary/website#1502] opened 2016-12-20 13:21 UTC
### Expected behavior

From UX point of view it would really be awesome if you could add Free download button to the page instead of typing "0" in donating input.

### Actual behavior

I know some people who wanted to try Elementary but they got scared of by Purchase options. It's not really visible that you can insert "0" and download it for free. I can see that being a problem.

### Steps to reproduce the behavior

1.  Next to purchase option add Free Download button

**Comment by cassidyjames** [comment] 2016-12-20 16:29
Duplicate of #342

**Closed by cassidyjames** 2016-12-20 16:29 UTC
