### ISSUE TITLE
Suggestion: Change from UNetbootin to Etcher for installation guide

### ISSUE THREAD

**Issue by tomphillpotts** [elementary/website#1862] opened 2017-12-28 04:36 UTC
Hello,
I just encountered Elementary for the first time. 
I have a small suggestion for the installation instructions. I recently discovered Etcher:

https://etcher.io/

It is ridiculously easy to use, and also looks sleek! I suggest changing your installation guide to recommend Etcher instead of UNetbootin. I have used UNetbootin before and it's not as simple and attractive as Etcher.

Thanks,
Tom Phillpotts
Christchurch, New Zealand

**Comment by jwinnie** [comment] 2018-01-05 18:46
I agree. For some reason, elementary recommends you to use Etcher for macOS but not for Ubuntu or Windows.

**Comment by btkostner** [comment] 2018-01-05 19:14
Marking as a duplicate of https://github.com/elementary/website/issues/1489

**Closed by btkostner** 2018-01-05 19:14 UTC
