### ISSUE TITLE
UK site defaults to Ukranian languague

### ISSUE THREAD

**Issue by Joe-Withey** [elementary/website#1826] opened 2017-09-28 14:10 UTC
### Expected behavior

English language on `/uk`.

### Actual behavior

When I got to [Elementary OS website](http://elementaryos.io) I get redirected to the `/uk` site but the language is Ukrainian.

### System information

- **Operating system**: Elementary OS 
- **Operating system version**: 0.4 Loki
- **Browser**: Chrome
- **Browser version**: 60.0.3112.101

**Comment by btkostner** [comment] 2017-09-28 17:59
The URL is working as intended. It's not for location, but for a language code. `uk` is the Ukrainian language code, so you are seeing the website translated.

Doing https://elementary.io/en/ will give you an English site. Otherwise you can use the language drop-down on the bottom of the page.

I'm curious as to why you were redirected though. Do you have a Ukrainian language in your browser settings? Are you living in an area that mostly speaks Ukrainian? Did you click a search engine link that has the `/uk/` part in the URL?

**Comment by btkostner** [comment] 2017-09-28 18:03
I'm going to close this as the URL part of the issue is working as intended.

Please continue discussing the redirect part, as that is not intended.

**Closed by btkostner** 2017-09-28 18:03 UTC
