### ISSUE TITLE
Update the description and screenshots in docs/learning-the-basics

### ISSUE THREAD

**Issue by ryonakano** [elementary/website#1984] opened 2018-07-05 10:48 UTC
Related #1850 & #1983.

I think we also need to update screenshots in docs/learning-the-basics because they are from Luna.
In addition that, we need to review and update the description after the release of Juno because there are some description for Loki:

> Note: Some software may not be available from AppCenter. While we don't recommend downloading software from the general Internet, **apps that are compatible with Ubuntu 16.04 LTS should work on elementary OS Loki**.

**Comment by ryonakano** [comment] 2019-02-12 06:46
The description was updated in #2158 but the screenshots still remain old.

**Comment by peteruithoven** [comment] 2019-04-25 14:49
Looks like, if this is now just about the screenshots, this is a duplicate of https://github.com/elementary/website/issues/1374

**Closed** 2019-04-25 14:50 UTC
