### ISSUE TITLE
The website does not display nicely over cellular data.

### ISSUE THREAD

**Issue by icelfio** [elementary/website#1438] opened 2016-10-14 11:00 UTC
la web es si esta muy bonito pero sobre en ordenadores, cuando uno entra la web mediante un celular es ven horribles  desde el menu.

**Comment by lewisgoddard** [comment] 2016-11-01 20:00
Would you be able to post what browser/OS you were using when you accessed the website?

**Comment by cassidyjames** [comment] 2017-01-01 05:18
A rough translation to English:

> The site is very nice, but only on computers [large displays]. When using a mobile device [small display], the menu is horrible.

I think the complaint is a dupe of #1344

**Closed** 2017-01-01 05:18 UTC
Labels: Status Incomplete
