### ISSUE TITLE
Download button not working

### ISSUE THREAD

**Issue by NielsenMax** [elementary/website#2210] opened 2019-06-01 01:01 UTC
### Expected behavior
Describe what you expected to happen.
Be able to download the iso
### Actual behavior
Describe what actually happened, being specific about how this differs from your expectations.
When you click the button it does nothing, even with any amount of money checked.

Console said this:
Uncaught (in promise) TypeError: Cannot read property 'title' of undefined
    at download.js:1

### Steps to reproduce the behavior
Just tried to download

### System information

- **Operating system**: Windows 10
- **Operating system version**: 
- **Browser**: Chrome
- **Browser version**: 
- **Enabled Browser Extensions**:

**Comment by rickychristensen** [comment] 2019-06-01 04:11
Same.
I have tried Firefox, Safari and Chrome on MacOS Mojave to no avail.

**Comment by ryonakano** [comment] 2019-06-01 04:13
Duplicate of #2201?

**Comment by danrabbit** [comment] 2019-06-01 16:58
Thanks for your report! However, this issue has already been reported and is being tracked elsewhere.

Closing as a Duplicate of #2201

**Closed by danrabbit** 2019-06-01 16:58 UTC
