### ISSUE TITLE
Clicking Code icon on homepage breaks the slideshow

### ISSUE THREAD

**Issue by jchannon** [elementary/website#2110] opened 2018-11-04 12:21 UTC
### Expected behavior

To show the code preview

### Actual behavior

Breaks slideshow and shows all arrows for all apps and puts preview images of all the apps on top of each other

### Steps to reproduce the behavior

1. Go to the main website
2. Scroll to area that lists the apps
3. Click Code app
4. BOOM

Example screenshot attached:

<img width="1626" alt="screen shot 2018-11-04 at 12 19 26" src="https://user-images.githubusercontent.com/105126/47964070-2fcdcf00-e02c-11e8-8016-c7da8d587c53.png">

### System information

- **Operating system**: Mac OS
- **Operating system version**: 10.12.6
- **Browser**: Chrome
- **Browser version**: 69
- **Enabled Browser Extensions**:

**Comment by peteruithoven** [comment] 2018-11-04 12:43
Thanks for the report! This is actually a duplicate of https://github.com/elementary/website/issues/2081

**Closed** 2018-11-04 13:35 UTC
Labels: Status: Duplicate
