### ISSUE TITLE
developer.elementary.io showing old version of elementary OS 

### ISSUE THREAD

**Issue by Git002** [elementary/website#2309] opened 2020-01-20 14:42 UTC
The website https://developer.elementary.io/ is showing old version of elementary OS i.e 5.0 Juno to be downloaded. Although new version has released (5.1 Hera). This may mislead them by downloading the older version. 
Just the text would need to be changed with the link to the button. 
Thanks

**Comment by danrabbit** [comment] 2020-02-14 21:50
Closing as a duplicate of https://github.com/elementary/houston/issues/765

**Closed by danrabbit** 2020-02-14 21:50 UTC
