### ISSUE TITLE
Clipped elementary Logo

### ISSUE THREAD

**Issue by Foggalong** [elementary/website#1703] opened 2017-05-15 18:18 UTC
Very minor, but there's a clipping issue on the SVG elementary logo for the [dev page](http://developer.elementary.io/) when viewing in Firefox. The left of the first e and the top of the last S are just missed out of the viewbox.

![screenshot_2017-05-15_19-10-05](https://cloud.githubusercontent.com/assets/5920259/26072351/12a5c418-39a3-11e7-98a7-d2a64cbb894b.png)

### System information

- **Operating system**: Ubuntu
- **Operating system version**: 17.04 
- **Browser**: Firefox
- **Browser version**: 53
- **Enabled Browser Extensions**: None

**Comment by btkostner** [comment] 2017-05-16 01:05
I'm running firefox 53 on Loki (Ubuntu 16.04) and I do not see this problem. I wonder if it's something weird upstream.

**Comment by lordfido** [comment] 2018-03-02 23:57
Cannot reproduce, Firefox 58 and elementary OS 0.4.1

**Comment by Foggalong** [comment] 2018-03-03 11:35
I can still reproduce this, on other distros too. This is Fedora 27:
![2018-03-03-113439_542x189_scrot](https://user-images.githubusercontent.com/5920259/36933783-eba6cd7a-1ed6-11e8-9173-d046ca7bbfb9.png)

**Comment by ryonakano** [comment] 2018-05-27 10:06
This issue is no longer able to confirm because the design of dev page was changed and the SVG elementary logo does not exist. I think it's better to close this issue, IMO.

**Comment by fabianthoma** [comment] 2018-05-27 12:03
I can confirm that the issue does not exist anymore because the Design got changed.

**Closed by fabianthoma** 2018-05-27 12:03 UTC

**Comment by ryonakano** [comment] 2018-05-27 12:30
Thank you
