### ISSUE TITLE
Trouble visiting elementary website from Egypt

### ISSUE THREAD

**Issue by MahmoudKhalil** [elementary/website#1735] opened 2017-05-30 14:10 UTC
Anyone having trouble visiting the website, I'm from Egypt and it seems to me that the website is down, I tried to reach it several time this month but I couldn't

I'm trying to reach it from Cairo, Egypt 
I'm using Ubuntu 14.04

**Comment by LeorioHisoka** [comment] 2017-05-30 20:03
it is also me too from Egypt and I have the same issue , I've searched/asked about this issue in the last few days , I found out that the issue is not in the whole Egypt , it dependence on what IPS you are using ,users on Facebook and my friends  have the same issue  with the same IPS , but other friends and users on Facebook from Egypt  with other IPSs don't have this issue , the problem is from teda** , I've emailed them but I got nothing yet , I used VPNs and the results are I got access to the website 

note : the problem is not with just only website it also with the repository
what should we do about that ?

**Comment by yarons** [comment] 2017-05-31 07:44
Works from Israel, BTW @MahmoudKhalil & @LeorioHisoka, can you please take a look at #1732 and add your insights?

**Comment by MahmoudKhalil** [comment] 2017-06-01 09:31
@LeorioHisoka I will try to contact them too and if anything new happens I'll let you know.

**Comment by LeorioHisoka** [comment] 2017-06-03 06:03
I just contacted them again , and at beginning of the typing  the website works 
now please check it out again

**Comment by btkostner** [comment] 2017-06-07 01:31
I'm going to close this because there is not much we can do with an ISP blocking our domain.

**Closed by btkostner** 2017-06-07 01:31 UTC
