### ISSUE TITLE
Make paypal available as a payment option

### ISSUE THREAD

**Issue by bigfatbird** [elementary/website#1639] opened 2017-04-09 00:06 UTC
Many people in Europe/Germany do not have a credit card. You lose money here!

Solution is to offer paypal (or something else, maybe debit) as a payment option.

**Comment by OT-World** [comment] 2017-04-09 04:48
Where it says custom just place a 0 in the box and then you will be able to download the file.

**Comment by bigfatbird** [comment] 2017-04-09 15:23
That was not my point. I am widely aware I can get it for free.

**Comment by lewisgoddard** [comment] 2017-04-09 19:26
Duplicate of #1441

**Closed by lewisgoddard** 2017-04-09 19:26 UTC
